install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip
  
script:
  - bin/protoc -I=. --java_out=. ./robot_communication_packet.proto
  - bin/protoc -I=. --cpp_out=. ./robot_communication_packet.proto
  - ls