language: java
jdk: openjdk7

install:
  - chmod +x gradlew

script:
  - ./gradlew clean

  # build protobuf using gradle
  - ./gradlew generateProto

  # build jars
  - ./gradlew -Ptag=$TRAVIS_TAG build
  - ./gradlew -Ptag=$TRAVIS_TAG shadowJar

  # zip cpp class
  - export CPP_ZIP_NAME=robot-communication-packet-proto-cpp-$TRAVIS_TAG.zip
  - echo $CPP_ZIP_NAME
  - export CPP_PATH=build/generated/source/proto/main/cpp
  - zip $CPP_ZIP_NAME $CPP_PATH/robot_comm_packet.pb.*

  # debug
  - find . -type f

deploy:
  provider: releases
  api_key:
    secure: WWZ0W8ncxMjMwYXYmNoyOQ9gLiXm0EWJvM55FeIvapgnWmbQ+VU8lWXDZiLQe8WvostQxqBS089IQq7pwEoT5yrhx65U1JOSR8Gs54SDt7RSgCbbgN89860sKrlrWYmvWkIiYciDGQ6ipEMUNuB4JjtWPDFpSo5+MMtSKQimZtJf5ILrzinAh6v+keAdPBtLk2NjvCJZ8hxo0a5LWy/D/OR04mRX8AibPnN4M6EutIfO9jteAqrZnX8DbXsqeVIfbzsUmcHB1YgVQJ47PiL90GCzFac09TdwP1tExi/3061qqTtAKLiboyL22eEku/7WcOIL8ZaI4TjRF2Fx5RqZ9UCHDZncsKDbvESYI7/i8g+5pld9zIDv264DGJtGWuQx11yjLGgPfI7Jg4v0VD9Rl+ewO8qveffIZe3zA6UC9zGJAtXOcJKcspLdADdpfqB+ffhpqiR8D4lHAarnXoq+sYW0MF4z+UsO6yzFYn1FaVsoHiG9Pzz4YEukEVIX3mFFrK4XLJgpKu8H0V2xXm3g2YtS0O/ThMbrg4NSLJ8isEGf8Rach0lhnkOgD7G1i2NKmpj5mRq7JxRjwJXNbAZ2hES+2XaOKZMsYvmikDVO8DPqeOtt0w1+NrugUbWDcPcpuQ6RCVmxtGuBhZRj+Hvmx5gh+a925LwoSRP6uELqXpE=
  file_glob: true
  file:
    - ./build/libs/robot-communication-packet-proto-*.jar
    - ./$CPP_ZIP_NAME
  skip_cleanup: true
  on:
    tags: true
    repo: nnadeau/robot-communication-packet-proto
notifications:
  email: false
